@Api_HostAddress = https://localhost:8080

Get {{Api_HostAddress}}/api/customer/1

###

Get {{Api_HostAddress}}/api/customer/all

###

Put {{Api_HostAddress}}/api/customer/search
Content-Type: application/json

{
  "email": "test@mail.com"
}

###

Post {{Api_HostAddress}}/api/customer
Content-Type: application/json

{
  "email": "test@mail.com"
}

###

Put {{Api_HostAddress}}/api/customer
Content-Type: application/json

{
  "id": 1,
  "item":
  {
    "email": "test@mail.com"
  }
}

###

Delete {{Api_HostAddress}}/api/customer/1

###
